/**
 * Large in-memory age-grouped fallback bank.
 * Used when AI fails/times out or DB pool is thin — never empty quizzes.
 */
import type { DifficultyLevel } from "@/lib/quiz/age-bands";
import { getAgeBand, shuffleInPlace } from "@/lib/quiz/age-bands";

export type FallbackQuestion = {
  publicId: string;
  text: string;
  options: string[];
  correctIndex: number;
  category: string;
  difficulty: DifficultyLevel;
  minAge: number;
  maxAge: number;
};

const FALLBACK: FallbackQuestion[] = [
  // 4–6 very_easy
  {
    publicId: "fb_ve_01",
    text: "What color is the sky on a sunny day?",
    options: ["Blue", "Green", "Black", "Purple"],
    correctIndex: 0,
    category: "nature",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_02",
    text: "How many legs does a dog have?",
    options: ["2", "4", "6", "8"],
    correctIndex: 1,
    category: "animals",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_03",
    text: "What is 1 + 1?",
    options: ["1", "2", "3", "4"],
    correctIndex: 1,
    category: "math",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_04",
    text: "Which animal says meow?",
    options: ["Dog", "Cat", "Cow", "Duck"],
    correctIndex: 1,
    category: "animals",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_05",
    text: "Which shape is round?",
    options: ["Square", "Triangle", "Circle", "Star"],
    correctIndex: 2,
    category: "shapes",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_06",
    text: "What do you drink when you are thirsty?",
    options: ["Water", "Sand", "Socks", "Paper"],
    correctIndex: 0,
    category: "daily",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_07",
    text: "Which fruit is red?",
    options: ["Banana", "Apple", "Blueberry", "Coconut"],
    correctIndex: 1,
    category: "food",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_08",
    text: "What is 2 + 2?",
    options: ["3", "4", "5", "6"],
    correctIndex: 1,
    category: "math",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_09",
    text: "Which one can fly?",
    options: ["Fish", "Bird", "Car", "Chair"],
    correctIndex: 1,
    category: "animals",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_10",
    text: "How many fingers on one hand?",
    options: ["3", "4", "5", "10"],
    correctIndex: 2,
    category: "body",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_11",
    text: "The sun gives us…",
    options: ["Light", "Snowballs", "Books", "Shoes"],
    correctIndex: 0,
    category: "nature",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },
  {
    publicId: "fb_ve_12",
    text: "Which is a color?",
    options: ["Happy", "Yellow", "Run", "Jump"],
    correctIndex: 1,
    category: "colors",
    difficulty: "very_easy",
    minAge: 4,
    maxAge: 6,
  },

  // 7–9 easy
  {
    publicId: "fb_ea_01",
    text: "What is 7 + 5?",
    options: ["10", "11", "12", "13"],
    correctIndex: 2,
    category: "math",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_02",
    text: "How many days are in one week?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_03",
    text: "Which planet do we live on?",
    options: ["Mars", "Earth", "Venus", "Jupiter"],
    correctIndex: 1,
    category: "science",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_04",
    text: "What is 15 − 6?",
    options: ["7", "8", "9", "10"],
    correctIndex: 2,
    category: "math",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_05",
    text: "Bees make…",
    options: ["Milk", "Honey", "Juice", "Butter"],
    correctIndex: 1,
    category: "nature",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_06",
    text: "A triangle has how many sides?",
    options: ["2", "3", "4", "5"],
    correctIndex: 1,
    category: "math",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_07",
    text: "Which animal is a mammal?",
    options: ["Shark", "Frog", "Dolphin", "Ant"],
    correctIndex: 2,
    category: "science",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_08",
    text: "What is 9 × 2?",
    options: ["16", "18", "20", "22"],
    correctIndex: 1,
    category: "math",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_09",
    text: "Water freezes into…",
    options: ["Steam", "Ice", "Sand", "Oil"],
    correctIndex: 1,
    category: "science",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_10",
    text: "Which word is a verb (action word)?",
    options: ["Happy", "Run", "Blue", "Soft"],
    correctIndex: 1,
    category: "english",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_11",
    text: "How many months are in a year?",
    options: ["10", "11", "12", "13"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },
  {
    publicId: "fb_ea_12",
    text: "Which is a healthy snack?",
    options: ["Candy only", "An apple", "Soda", "Chips only"],
    correctIndex: 1,
    category: "health",
    difficulty: "easy",
    minAge: 7,
    maxAge: 9,
  },

  // 10–12 moderate
  {
    publicId: "fb_mo_01",
    text: "What is 12 × 8?",
    options: ["86", "96", "106", "88"],
    correctIndex: 1,
    category: "math",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_02",
    text: "What is 3/4 of 20?",
    options: ["10", "12", "15", "16"],
    correctIndex: 2,
    category: "math",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_03",
    text: "Which gas do plants take in for photosynthesis?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"],
    correctIndex: 2,
    category: "science",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_04",
    text: "The capital of France is…",
    options: ["Lyon", "Paris", "Nice", "Marseille"],
    correctIndex: 1,
    category: "geography",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_05",
    text: "A synonym of “happy” is…",
    options: ["Angry", "Joyful", "Tiny", "Slow"],
    correctIndex: 1,
    category: "english",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_06",
    text: "How many degrees are in a right angle?",
    options: ["45", "90", "180", "360"],
    correctIndex: 1,
    category: "math",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_07",
    text: "Which organ pumps blood?",
    options: ["Lungs", "Heart", "Stomach", "Brain"],
    correctIndex: 1,
    category: "science",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_08",
    text: "What is 144 ÷ 12?",
    options: ["10", "11", "12", "14"],
    correctIndex: 2,
    category: "math",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_09",
    text: "Which continent is Egypt in?",
    options: ["Asia", "Europe", "Africa", "Australia"],
    correctIndex: 2,
    category: "geography",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_10",
    text: "An antonym of “hot” is…",
    options: ["Warm", "Cold", "Bright", "Loud"],
    correctIndex: 1,
    category: "english",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_11",
    text: "Water boils at sea level at about…",
    options: ["50°C", "80°C", "100°C", "200°C"],
    correctIndex: 2,
    category: "science",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },
  {
    publicId: "fb_mo_12",
    text: "What is 25% of 80?",
    options: ["15", "20", "25", "40"],
    correctIndex: 1,
    category: "math",
    difficulty: "moderate",
    minAge: 10,
    maxAge: 12,
  },

  // 13–15 intermediate
  {
    publicId: "fb_in_01",
    text: "Solve for x: 2x + 6 = 20",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
    category: "math",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_02",
    text: "What is the chemical formula for water?",
    options: ["CO2", "H2O", "O2", "NaCl"],
    correctIndex: 1,
    category: "science",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_03",
    text: "π (pi) is approximately…",
    options: ["2.14", "3.14", "4.14", "1.41"],
    correctIndex: 1,
    category: "math",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_04",
    text: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Mercury", "Saturn"],
    correctIndex: 1,
    category: "science",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_05",
    text: "A hexagon has how many sides?",
    options: ["5", "6", "7", "8"],
    correctIndex: 1,
    category: "math",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_06",
    text: "Photosynthesis mainly happens in a plant’s…",
    options: ["Roots", "Leaves", "Flowers", "Seeds"],
    correctIndex: 1,
    category: "science",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_07",
    text: "What is 15% of 200?",
    options: ["20", "25", "30", "35"],
    correctIndex: 2,
    category: "math",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_08",
    text: "Which word is a noun?",
    options: ["Quickly", "Beautiful", "Library", "Run"],
    correctIndex: 2,
    category: "english",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_09",
    text: "The largest ocean on Earth is the…",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    correctIndex: 3,
    category: "geography",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_10",
    text: "If a triangle has angles 40° and 60°, the third is…",
    options: ["70°", "80°", "90°", "100°"],
    correctIndex: 1,
    category: "math",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_11",
    text: "DNA is found mainly in a cell’s…",
    options: ["Membrane", "Nucleus", "Cytoplasm wall only", "Vacuole only"],
    correctIndex: 1,
    category: "science",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },
  {
    publicId: "fb_in_12",
    text: "Square root of 81 is…",
    options: ["7", "8", "9", "10"],
    correctIndex: 2,
    category: "math",
    difficulty: "intermediate",
    minAge: 13,
    maxAge: 15,
  },

  // 16+ advanced
  {
    publicId: "fb_ad_01",
    text: "Derivative of x² with respect to x is…",
    options: ["x", "2x", "x²", "2"],
    correctIndex: 1,
    category: "math",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_02",
    text: "In binary, 1010 equals decimal…",
    options: ["8", "9", "10", "12"],
    correctIndex: 2,
    category: "cs",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_03",
    text: "Speed of light in vacuum is about…",
    options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁴ m/s", "3×10² m/s"],
    correctIndex: 0,
    category: "science",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_04",
    text: "Solve: 3(x − 2) = 15",
    options: ["5", "6", "7", "9"],
    correctIndex: 2,
    category: "math",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_05",
    text: "HTTP status 404 means…",
    options: ["OK", "Forbidden", "Not Found", "Server Error"],
    correctIndex: 2,
    category: "cs",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_06",
    text: "Avogadro’s number is approximately…",
    options: ["6.02×10²³", "3.14×10⁸", "9.8×10¹", "1.6×10⁻¹⁹"],
    correctIndex: 0,
    category: "science",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_07",
    text: "log₁₀(1000) equals…",
    options: ["2", "3", "4", "10"],
    correctIndex: 1,
    category: "math",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_08",
    text: "Which layer of Earth is liquid metal?",
    options: ["Crust", "Mantle", "Outer core", "Inner core"],
    correctIndex: 2,
    category: "science",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_09",
    text: "In a right triangle, sin(θ) = opposite / …",
    options: ["Adjacent", "Hypotenuse", "Opposite", "Area"],
    correctIndex: 1,
    category: "math",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_10",
    text: "Photosynthesis equation product that animals breathe is…",
    options: ["CO₂", "O₂", "N₂", "CH₄"],
    correctIndex: 1,
    category: "science",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_11",
    text: "Big-O of binary search is…",
    options: ["O(n)", "O(log n)", "O(n²)", "O(1)"],
    correctIndex: 1,
    category: "cs",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
  {
    publicId: "fb_ad_12",
    text: "If f(x)=2x+1, f(4) equals…",
    options: ["7", "8", "9", "10"],
    correctIndex: 2,
    category: "math",
    difficulty: "advanced",
    minAge: 16,
    maxAge: 120,
  },
];

export function getFallbackQuestionsForAge(age: number, count: number, excludePublicIds: Set<string> = new Set()) {
  const band = getAgeBand(age);
  if (!band) return [];

  const primary = FALLBACK.filter(
    (q) => q.difficulty === band.difficulty && age >= q.minAge && age <= q.maxAge && !excludePublicIds.has(q.publicId)
  );
  const softer = FALLBACK.filter(
    (q) =>
      q.difficulty !== band.difficulty &&
      age >= q.minAge &&
      q.maxAge <= band.maxAge &&
      !excludePublicIds.has(q.publicId)
  );

  const picked = [...shuffleInPlace(primary), ...shuffleInPlace(softer)].slice(0, count);
  return picked;
}

export function getAllFallbackQuestions() {
  return FALLBACK.slice();
}
